version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /workspace/frontend/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_OPENAI_API_KEY=
    ports:
      - "3000:3000"
    networks:
      - mailcraft-network
    user: node

networks:
  mailcraft-network:
    driver: bridge 